# Generated by Django 6.0 on 2025-12-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text='Changed fields: old vs new values', null=True),
        ),
    ]
