# Generated by Django 6.0 on 2026-01-04 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_auditlog_changes'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A human-readable summary of the action.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(db_index=True, default='', help_text="Name of the resource (e.g., 'Product', 'Order', 'User')", max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(db_index=True, default='INFO', help_text='SUCCESS | FAILED | INFO', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='When the action occurred (renamed from created_at)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, help_text='create | update | delete | restore | hard_delete | USER_LOGIN | ...', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source',
            field=models.CharField(db_index=True, default='api', help_text='admin | api | shell', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
