# Generated by Django 6.0 on 2026-01-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0005_alter_auditlog_action_alter_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(default='INFO', max_length=10),
        ),
    ]
